server:
  port: 56081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:56080/eureka/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.10:3306/seata_demo_bank1?useUnicode=true&characterEncoding=utf8
    username: lypgod
    password: 123456
  jpa:
    show-sql: true

org:
  dromara:
    hmily:
      serializer: kryo
      recoverDelayTime: 120
      retryMax: 3
      scheduledDelay: 120
      scheduledThreadMax: 4
      repositorySupport: db
      started: true
      hmilyDbConfig:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.2.10:3306/hmily?useUnicode=true&characterEncoding=utf8
        username: lypgod
        password: 123456