server:
  port: 56081
  servlet:
    context-path: /account

spring:
  application:
    name: notifymsg-demo-account
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.10:3306/nofifymsg_demo_account?useUnicode=true&characterEncoding=utf8
    username: lypgod
    password: 123456
  jpa:
    show-sql: true

rocketmq:
  producer:
    group: producer_notifymsg_account
  name-server: 192.168.2.10:9876

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:56080/eureka/
